### ISSUE TITLE
I would like to contact you

### ISSUE THREAD

**Issue by jaizpuruzin** [dapperfu/mi_analysis#1]
Good morning from San Sebastian, Spain

I am writing to you as I need support for these tools:
https://github.com/rettichschnidi/clang-tidy-misra
or else,
https://github.com/rettichschnidi/clang-misracpp2008
I have seen that you were able to implement it and could you help me a bit with the steps you followed to run it?
I am a software engineer with more than 5 years of experience in railway projects and I am currently working in the company CEIT trying to launch misra rules "for free" in order to get more experience in the static analysis sector.
I would be very grateful if I could contact you to ask for some support.

Thank you very much and whatever you need from me I would be grateful to give you support or help you.
I also leave you my linkedin:
https://www.linkedin.com/in/joanes-aizpuru-zinkunegi-a06b86164/

**Comment by dapperfu** [comment]
I haven't used either of those in a while. Looking at the last commit dates they are likely out of date with the latest clang.

There is cppcheck https://github.com/danmar/cppcheck/ which has MISRA support.

**Comment by jaizpuruzin** [comment]
Yes, I have already used cppcheck but it does not cover the MISRA C++ 2008 rules but it seems that the one you used does.

Do you remember the version of clang you used? Also, do you remember the steps you took to get it up and running?

Thank you very much for your answer!

Joanes
